[General]
background=background.jpg
currentWallpaper=file:///var/tmp/odyssey-sddm-current-wallpaper
surface=#101418
surfaceHigh=#272a2f
text=#e1e2e8
textMuted=#c3c7cf
outline=#42474e
primary=#9fcafd
error=#ffb4ab
warning=#f4c46b
dimmer=#8c101418
blurRadius=24
blurEnabled=true
fontFamily=Adwaita Sans
monoFontFamily=JetBrainsMono Nerd Font
