#!/usr/bin/env bash
set -euo pipefail

project_dir=$(cd "$(dirname "$0")/.." && pwd)
state_root=${XDG_STATE_HOME:-"${HOME:?HOME is required}/.local/state"}
palette=${1:-"$state_root/odyssey/palette.json"}
fallback_palette="$project_dir/generated/palette.json"
mode=${2:-dark}
output_dir=${3:-"$state_root/odyssey/theme-exports"}
hyprlock_active=${4:-false}

if [[ "$mode" != "dark" && "$mode" != "light" ]]; then
    printf 'theme mode must be dark or light: %s\n' "$mode" >&2
    exit 2
fi
if [[ $hyprlock_active != true && $hyprlock_active != false ]]; then
    printf 'hyprlock activation must be true or false\n' >&2
    exit 2
fi
if [[ ! -f "$palette" ]]; then
    printf 'palette not found: %s\n' "$palette" >&2
    exit 1
fi
if [[ -z "$output_dir" || "$output_dir" == "/" ]]; then
    printf 'refusing unsafe theme export directory: %s\n' "$output_dir" >&2
    exit 2
fi
command -v jq >/dev/null || {
    printf 'jq is required to export Odyssey themes\n' >&2
    exit 1
}
if [[ ! -f $palette ]] || ! jq -e '.mode and (.dark | type == "object") and (.light | type == "object")' "$palette" >/dev/null 2>&1; then
    palette=$fallback_palette
fi

required_tokens=(
    primary onPrimary primaryContainer onPrimaryContainer secondary tertiary
    surface surfaceContainerLow surfaceContainer surfaceContainerHigh
    onSurface onSurfaceVariant outline outlineVariant error warning success
)
tokens_json=$(printf '%s\n' "${required_tokens[@]}" | jq -R . | jq -s .)
# The dollar-prefixed names below belong to jq, not the shell.
# shellcheck disable=SC2016
jq_filter='. as $root | type == "object" and all($tokens[];
    . as $token | $root[$mode][$token] | strings | test("^#[0-9a-fA-F]{6}$"))'
jq -e --arg mode "$mode" --argjson tokens "$tokens_json" \
    "$jq_filter" "$palette" >/dev/null

declare -A colors
for token in "${required_tokens[@]}"; do
    colors[$token]=$(jq -er --arg mode "$mode" --arg token "$token" \
        '.[$mode][$token]' "$palette")
done

hex() {
    printf '%s' "${1#\#}"
}

mkdir -p "$output_dir"
stage_dir=$(mktemp -d "$output_dir/.export.XXXXXX")
trap 'rm -rf "$stage_dir"' EXIT

jq --arg mode "$mode" '.[$mode] + { mode: $mode }' "$palette" \
    > "$stage_dir/tokens.json"

{
    printf '# Generated by Odyssey. This file only defines variables.\n'
    printf '# Source it explicitly from Hyprland when the integration is enabled.\n\n'
    for token in "${required_tokens[@]}"; do
        # shellcheck disable=SC2016
        printf '$odyssey_%s = rgb(%s)\n' "$token" "$(hex "${colors[$token]}")"
    done
} > "$stage_dir/hyprland.conf"

{
    printf '# Generated by Odyssey. This file only defines variables.\n'
    printf '# Source it explicitly from Hyprlock when the integration is enabled.\n\n'
    for token in "${required_tokens[@]}"; do
        # shellcheck disable=SC2016
        printf '$odyssey_%s = rgb(%s)\n' "$token" "$(hex "${colors[$token]}")"
    done
} > "$stage_dir/hyprlock.conf"

{
    printf '/* Generated Odyssey semantic colors; inert until explicitly imported. */\n'
    for token in "${required_tokens[@]}"; do
        printf '@define-color odyssey_%s %s;\n' "$token" "${colors[$token]}"
    done
} > "$stage_dir/gtk.css"

{
    printf '# Generated Odyssey Kitty palette; inert until explicitly included.\n'
    printf 'foreground %s\n' "${colors[onSurface]}"
    printf 'background %s\n' "${colors[surface]}"
    printf 'selection_foreground %s\n' "${colors[onPrimaryContainer]}"
    printf 'selection_background %s\n' "${colors[primaryContainer]}"
    printf 'cursor %s\n' "${colors[primary]}"
    printf 'cursor_text_color %s\n' "${colors[onPrimary]}"
    printf 'url_color %s\n' "${colors[secondary]}"
    printf 'active_tab_background %s\n' "${colors[primaryContainer]}"
    printf 'active_tab_foreground %s\n' "${colors[onPrimaryContainer]}"
    printf 'inactive_tab_background %s\n' "${colors[surfaceContainerHigh]}"
    printf 'inactive_tab_foreground %s\n' "${colors[onSurfaceVariant]}"
    printf 'tab_bar_background %s\n\n' "${colors[surfaceContainerLow]}"
    printf 'color0 %s\n' "${colors[surfaceContainerLow]}"
    printf 'color1 %s\n' "${colors[error]}"
    printf 'color2 %s\n' "${colors[success]}"
    printf 'color3 %s\n' "${colors[warning]}"
    printf 'color4 %s\n' "${colors[primary]}"
    printf 'color5 %s\n' "${colors[tertiary]}"
    printf 'color6 %s\n' "${colors[secondary]}"
    printf 'color7 %s\n' "${colors[onSurface]}"
    printf 'color8 %s\n' "${colors[outline]}"
    printf 'color9 %s\n' "${colors[error]}"
    printf 'color10 %s\n' "${colors[success]}"
    printf 'color11 %s\n' "${colors[warning]}"
    printf 'color12 %s\n' "${colors[primaryContainer]}"
    printf 'color13 %s\n' "${colors[tertiary]}"
    printf 'color14 %s\n' "${colors[secondary]}"
    printf 'color15 %s\n' "${colors[onSurfaceVariant]}"
} > "$stage_dir/kitty.conf"

# Fastfetch's JSONC configuration remains user-owned.  This small descriptor is
# consumed only by its opt-in ownership helper, which updates existing visual
# fields without changing the user's module list or output colours.
jq -n --arg mode "$mode" --arg accent "${colors[primary]}" \
    '{version: 1, mode: $mode, accent: $accent}' > "$stage_dir/fastfetch.json"

generated_at=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
jq -n \
    --arg mode "$mode" \
    --arg palette "$palette" \
    --arg generatedAt "$generated_at" \
    --argjson hyprlockActive "$hyprlock_active" \
    '{
        version: 1,
        mode: $mode,
        sourcePalette: $palette,
        generatedAt: $generatedAt,
        active: $hyprlockActive,
        integrations: { hyprlock: $hyprlockActive },
        files: {
            tokens: "tokens.json",
            hyprland: "hyprland.conf",
            hyprlock: "hyprlock.conf",
            gtk: "gtk.css",
            kitty: "kitty.conf",
            fastfetch: "fastfetch.json"
        }
    }' > "$stage_dir/manifest.json"

for name in tokens.json hyprland.conf hyprlock.conf gtk.css kitty.conf fastfetch.json manifest.json; do
    chmod 0644 "$stage_dir/$name"
    mv -f "$stage_dir/$name" "$output_dir/$name"
done

# Starship has no TOML import/merge support.  Its opt-in helper therefore owns
# one guarded block inside the user config and is a no-op until explicitly enabled.
"$project_dir/scripts/starship-themectl.py" refresh "$palette" "$mode" >/dev/null
"$project_dir/scripts/kitty-themectl.py" refresh >/dev/null
"$project_dir/scripts/fastfetch-themectl.py" refresh >/dev/null

if [[ $hyprlock_active == true ]]; then
    "$project_dir/scripts/generate-hyprlock-config.sh" "$palette" "$mode" \
        "$state_root/odyssey/hyprlock.conf" "$output_dir/hyprlock.conf" \
        >/dev/null
fi

printf 'EXPORTED=%s\n' "$output_dir"
printf 'MODE=%s\n' "$mode"
printf 'ACTIVE=%s\n' "$hyprlock_active"
