#!/usr/bin/env bash
set -euo pipefail

project_dir=$(cd "$(dirname "$0")/.." && pwd)
state_root=${XDG_STATE_HOME:-"${HOME:?HOME is required}/.local/state"}
palette=${1:-"$state_root/odyssey/palette.json"}
[[ -f $palette ]] || palette="$project_dir/generated/palette.json"
mode=${2:-dark}
output=${3:-"$state_root/odyssey/hyprlock.conf"}
theme_file=${4:-"$state_root/odyssey/theme-exports/hyprlock.conf"}

[[ $mode == dark || $mode == light ]] || {
  printf 'lock theme mode must be dark or light\n' >&2
  exit 2
}
[[ -f $palette ]] || {
  printf 'lock palette not found: %s\n' "$palette" >&2
  exit 1
}
command -v jq >/dev/null || {
  printf 'jq is required to generate the lock configuration\n' >&2
  exit 1
}
if [[ -z $output || $output == / ]]; then
  printf 'refusing unsafe lock configuration path: %s\n' "$output" >&2
  exit 2
fi

color() {
  jq -er --arg mode "$mode" --arg token "$1" \
    '.[$mode][$token] | strings | select(test("^#[0-9a-fA-F]{6}$"))' \
    "$palette"
}

hex() {
  printf '%s' "${1#\#}"
}

wallpaper=$("$project_dir/scripts/lock-status.sh" wallpaper)
identity=$("$project_dir/scripts/lock-status.sh" identity)
[[ -f $wallpaper ]] || wallpaper="screenshot"

primary=$(hex "$(color primary)")
surface=$(hex "$(color surface)")
surface_high=$(hex "$(color surfaceContainerHigh)")
surface_text=$(hex "$(color onSurface)")
surface_variant=$(hex "$(color onSurfaceVariant)")
outline=$(hex "$(color outlineVariant)")
error=$(hex "$(color error)")
warning=$(hex "$(color warning)")

mkdir -p "$(dirname "$output")"
temporary=$(mktemp "$(dirname "$output")/.hyprlock.XXXXXX.conf")
trap 'rm -f "$temporary"' EXIT

cat >"$temporary" <<EOF
# Generated by Odyssey. Authentication remains owned by Hyprlock and PAM.
# Regenerate this file; do not hand-edit it.
source = $theme_file

\$font = Adwaita Sans
\$mono = JetBrainsMono Nerd Font
\$status = odyssey lock-status
\$power = odyssey lock-power

general {
    hide_cursor = false
    immediate_render = true
}

animations {
    enabled = true
    bezier = odyssey, 0.22, 1, 0.36, 1
    animation = fadeIn, 1, 3, odyssey
    animation = fadeOut, 1, 3, odyssey
    animation = inputFieldDots, 1, 2, odyssey
    animation = inputFieldFade, 1, 3, odyssey
    animation = inputFieldColors, 1, 2, odyssey
}

background {
    monitor =
    path = $wallpaper
    color = rgb($surface)
    blur_passes = 3
    blur_size = 7
    noise = 0.008
    contrast = 0.96
    brightness = 0.46
    vibrancy = 0.10
    vibrancy_darkness = 0.08
    reload_time = 2
    reload_cmd = \$status wallpaper
}

image {
    monitor =
    path = $identity
    size = 110
    rounding = -1
    border_size = 2
    border_color = rgba(${outline}cc)
    shadow_passes = 2
    shadow_size = 7
    shadow_color = rgba(${surface}99)
    reload_time = 2
    reload_cmd = \$status identity
    position = 0, 72
    halign = center
    valign = center
}

label {
    monitor =
    text = \$TIME
    color = rgb($surface_text)
    font_size = 72
    font_family = \$mono
    shadow_passes = 2
    shadow_size = 6
    shadow_color = rgba(${surface}aa)
    position = 0, 268
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d"
    color = rgb($surface_variant)
    font_size = 16
    font_family = \$mono
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(${surface}aa)
    position = 0, 208
    halign = center
    valign = center
}

#label {
#    monitor =
#    text = $USER
#    color = rgb($surface_text)
#    font_size = 16
#    font_family = \$font
#    shadow_passes = 2
#    shadow_size = 5
#    shadow_color = rgba(${surface}aa)
#    position = 0, -18
#    halign = center
#    valign = center
#}

input-field {
    monitor =
    size = 460, 56
    outline_thickness = 1
    dots_size = 0.15
    dots_spacing = 0.28
    outer_color = rgba(${outline}cc)
    inner_color = rgba(${surface_high}20)
    font_color = rgb($surface_text)
    font_family = \$mono
    fade_on_empty = true
    fade_timeout = 3200
    placeholder_text = <span foreground="##$surface_variant">...</span>
    rounding = -1
    check_color = rgb($primary)
    check_text = <span foreground="##$surface_variant">authenticating…</span>
    fail_color = rgb($error)
    fail_text = <span foreground="##$error">failed.</span>
    capslock_color = rgb($warning)
    position = 0, -92
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:120000] \$status weather
    color = rgb($surface_variant)
    font_size = 14
    font_family = \$mono
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(${surface}aa)
    position = 32, -30
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:10000] \$status battery
    color = rgb($surface_text)
    font_size = 14
    font_family = \$mono
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(${surface}aa)
    position = -32, -30
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:2000] \$status media
    color = rgb($surface_variant)
    font_size = 14
    font_family = \$font
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(${surface}aa)
    position = 0, -150
    halign = center
    valign = center
}

label {
    monitor =
    text =
    color = rgba(${surface_variant}bb)
    font_size = 12
    font_family = \$mono
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(${surface}aa)
    position = 0, -138
    halign = center
    valign = center
}

# Hyprlock provides the click target; Odyssey keeps the menu state and dispatch
# in a fixed-action helper so no arbitrary command can be armed from the lock
# screen. Empty dynamic labels collapse until the power glyph opens the menu.
label {
    monitor =
    text = 󰐥
    color = rgb($surface_text)
    font_size = 20
    font_family = \$mono
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(${surface}aa)
    onclick = \$power toggle
    position = -32, 30
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0:1] \$power label suspend
    color = rgb($surface_text)
    font_size = 14
    font_family = \$mono
    onclick = \$power action suspend
    position = -32, 68
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0:1] \$power label hibernate
    color = rgb($surface_text)
    font_size = 14
    font_family = \$mono
    onclick = \$power action hibernate
    position = -32, 96
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0:1] \$power label logout
    color = rgb($surface_text)
    font_size = 14
    font_family = \$mono
    onclick = \$power action logout
    position = -32, 124
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0:1] \$power label reboot
    color = rgb($surface_text)
    font_size = 14
    font_family = \$mono
    onclick = \$power action reboot
    position = -32, 152
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0:1] \$power label shutdown
    color = rgb($error)
    font_size = 14
    font_family = \$mono
    onclick = \$power action shutdown
    position = -32, 180
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0:1] \$power label confirm-hibernate
    color = rgb($warning)
    font_size = 14
    font_family = \$mono
    onclick = \$power confirm hibernate
    position = -32, 68
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0:1] \$power label confirm-logout
    color = rgb($warning)
    font_size = 14
    font_family = \$mono
    onclick = \$power confirm logout
    position = -32, 68
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0:1] \$power label confirm-reboot
    color = rgb($warning)
    font_size = 14
    font_family = \$mono
    onclick = \$power confirm reboot
    position = -32, 68
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0:1] \$power label confirm-shutdown
    color = rgb($error)
    font_size = 14
    font_family = \$mono
    onclick = \$power confirm shutdown
    position = -32, 68
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0:1] \$power label cancel
    color = rgb($surface_variant)
    font_size = 14
    font_family = \$mono
    onclick = \$power cancel
    position = -32, 96
    halign = right
    valign = bottom
}
EOF

chmod 0600 "$temporary"
mv -f "$temporary" "$output"
trap - EXIT
printf 'CONFIG=%s\n' "$output"
