#!/usr/bin/env bash
set -euo pipefail

command_name=${1:-}
config_root=${XDG_CONFIG_HOME:-"$HOME/.config"}
state_root=${XDG_STATE_HOME:-"$HOME/.local/state"}
generated_dir="$state_root/odyssey"
generated_config="$generated_dir/hypridle.conf"
override_dir="$config_root/systemd/user/hypridle.service.d"
override_file="$override_dir/odyssey.conf"
service_command='ExecStart=/bin/sh -c '\''exec "$${XDG_BIN_HOME:-$${HOME}/.local/bin}/odyssey" hypridle'\'''
brightness_helper='odyssey idle-brightness'

managed() {
    [[ -f $generated_config && -f $override_file ]] \
        && grep -Fqx -- "$service_command" \
            "$override_file"
}

reload_service() {
    systemctl --user daemon-reload
}

case $command_name in
    status)
        if managed; then
            printf 'MANAGED=true\n'
        else
            printf 'MANAGED=false\n'
        fi
        ;;
    apply)
        (( $# == 7 )) || {
            printf 'Expected dim, lock, display-off, suspend, hibernate, and dim-percent values\n' >&2
            exit 2
        }
        dim=$2 lock=$3 display_off=$4 suspend=$5 hibernate=$6 dim_percent=$7
        for value in "$dim" "$lock" "$display_off" "$suspend" "$hibernate" "$dim_percent"; do
            [[ $value =~ ^[0-9]+$ ]] || {
                printf 'Idle policy values must be positive integers\n' >&2
                exit 2
            }
        done
        for timeout in "$dim" "$lock" "$display_off" "$suspend" "$hibernate"; do
            (( timeout >= 60 && timeout <= 59940 )) || {
                printf 'Idle timeouts must be between 1 and 999 minutes\n' >&2
                exit 2
            }
        done
        (( dim_percent >= 5 && dim_percent <= 90 )) || {
            printf 'Dim brightness must be between 5 and 90 percent\n' >&2
            exit 2
        }
        (( dim <= lock && lock <= display_off && display_off <= suspend \
            && suspend <= hibernate )) || {
            printf 'Idle stages must be ordered from dim through hibernate\n' >&2
            exit 2
        }
        mkdir -p -- "$generated_dir" "$override_dir"
        work_config=$(mktemp "$generated_dir/hypridle.conf.XXXXXX")
        work_override=$(mktemp "$override_dir/odyssey.conf.XXXXXX")
        trap 'rm -f -- "$work_config" "$work_override"' EXIT
        {
            printf '%s\n' '# Generated by Odyssey. Edit timing in Odyssey Settings.'
            printf '%s\n' 'general {'
            printf '%s\n' '    ignore_dbus_inhibit = false'
            printf '%s\n' '    ignore_systemd_inhibit = false'
            printf '%s\n' '    lock_cmd = pidof hyprlock || hyprlock'
            printf '%s\n' '    before_sleep_cmd = loginctl lock-session'
            printf '%s\n' '    after_sleep_cmd = hyprctl dispatch dpms on'
            printf '%s\n' '}'
            printf '\nlistener {\n    timeout = %s\n' "$dim"
            printf '    on-timeout = %s dim %s\n' "$brightness_helper" "$dim_percent"
            printf '    on-resume = %s restore\n' "$brightness_helper"
            printf '%s\n' '}'
            printf '\nlistener {\n    timeout = %s\n' "$lock"
            printf '%s\n' '    on-timeout = loginctl lock-session' '}'
            printf '\nlistener {\n    timeout = %s\n' "$display_off"
            printf '%s\n' '    on-timeout = hyprctl dispatch dpms off' \
                '    on-resume = hyprctl dispatch dpms on && brightnessctl -r' '}'
            printf '\nlistener {\n    timeout = %s\n' "$suspend"
            printf '%s\n' '    on-timeout = systemctl suspend' '}'
            printf '\nlistener {\n    timeout = %s\n' "$hibernate"
            printf '%s\n' '    on-timeout = systemctl hibernate' '}'
        } > "$work_config"
        {
            printf '%s\n' '[Unit]' 'StartLimitIntervalSec=10s' \
                'StartLimitBurst=12' '' '[Service]' 'ExecStart='
            printf '%s\n' "$service_command"
        } > "$work_override"
        mv -f -- "$work_config" "$generated_config"
        mv -f -- "$work_override" "$override_file"
        trap - EXIT
        reload_service
        systemctl --user reset-failed hypridle.service
        systemctl --user enable hypridle.service
        systemctl --user restart hypridle.service
        printf 'MANAGED=true\n'
        ;;
    remove)
        if [[ -f $override_file ]]; then
            rm -f -- "$override_file"
            rmdir --ignore-fail-on-non-empty "$override_dir" 2>/dev/null || true
        fi
        rm -f -- "$generated_config"
        reload_service
        systemctl --user try-restart hypridle.service
        printf 'MANAGED=false\n'
        ;;
    *)
        printf 'usage: %s {status|apply|remove} [VALUES...]\n' "$0" >&2
        exit 2
        ;;
esac
